followers = [
   "tornatovanroosmalen", "sabinalulu",
    "alhadi2134", "jeanmarceljm", "keegangerard", "kbix9", "lostboysskt", "ribeiroo_marcelo", "neto_taipu", "a1s_b2p", "hider.hider.hider", "benjaminjamesmusic", "docschlok",
    "stef_anie016","los_atunes", "heloisahfs", "surfingsport.of.ig", "alefmachadolive", "lorenzocomercio", "ericapoltronieri", "aurea.nica",
    "alan.moura83", "tarcearenee", "mseyez", "felipe.mr32015", "paulosol_gv", "ricojamesvt", "only_nady27", "iday.bd", "_lili_dupouy", "midnightandre", "nyfamarre", "kallebinhu.u",
    "ariadnacrowford", "surfholidaysericeira", "haribohabibo",
    "helder.santos.porto_portugal", "peppish", "louna_surf", "emily_see14", "feelgood_official", "hrnnch08", "chasing_world_surf", "songsandwhispers",
    "henrikljungqvist", "relogio_dos_reis", "rinaloha_", "hbayoubdental",
    "mozzgrl24", "thesurfcouple", "christopher.mcallaster", "ruymanrey","rodrigof.rch","denise_waitley_", "ibrahim_shimau", "rabbito12",
    "nightrengo35", "_nefes1m_", "thegrenaways", "aldenorzinho_freitas", "fonsecaluann", "projetomarujo", "hikingloverszone", "renee_hathaway_bridal",
    "enjoliecouture", "hebert_aalmeida", "josevictorbatista","andrew.moss12", "raphael_lampe__", "kzwavy",
    "cocomamabaleal", "uranapak", "negimukeshsingh077", "byronsurfergrom", "paulkappas1", "melky_808kyrel", "m_castillo63", "guinov75",
"dayanesantos197", "trias_travelista", "xande_olivera", "xride_ocean_emotion", "cello_dennise", "jasperhoekstra", "vitorscaramussa", "kiwoong___lee", "backcreek.customfishingrods",
    "yuliuz_7", "pedro888886", "nhall_abidin", "van_revitti", "gutorinaldi87", "al_taylor34", "lua_galaticavermelha", "natyy_placido", "joey1992hawkins", "recreiosharks",
    "5aseclinhares", "boutiquedoacabamento", "wani_fishing_apparel", "safraagronegociooficial", "rubiaterapeutacapilar", "cherrylinhares1", "al.essandra1734", "reatordesignweb",
    "oceansurfclass", "tony_joias", "leonardopereira.odontologia", "drvaldircampos", "senssavida", "espacowish", "luz.arquitetura", "_rangelnobre", "cali_connoisseurs",
    "quiosque_fundodequintal","insidemdigital", "jdssanclemente", "marcelecataldo", "boardroomshow", "adrian_surfman", "caicarabeach", "surf.harmony", "springvibez",  "mormaii_canoas",
    "408her.o", "surfexchange", "northbeachnutrition", "surfingnews_",  "oticascarolexclusive", "verbrisevix", "renatoleitesurfpower", "nick_tokona", "pies4thepeople",
 "ce.gaminarax", "tishchenko7201", "edermoledo", "asanasaf3.11", "kahunasurftripping", "siacatostefany", "luz_sommi2",
 "_benature", "acouguecareta", "dayane_higurashy",
 "sebastiaobatistatete", "infoco_colunasocial", "_riccardoarbia_", "raphaelfsales", "taquettivariedades", "sera_c_",
 "lamafellas", "qqqqquuiiiiitttyyt", "nardson_medeiros",
    "mrsyoungblood17", "joaojoao_alves", "bangalowave", "dalifoti", "seth_hart_igan", "i7_illustration", "gonzaloibarra82", "djan_kurt", "leys79", "alex.mini12", "montanniehill",
 "tikomanganelli", "solcorrales02", "sebasmorals95", "surfguru222", "neowalksticks", "milhemadam", "naoki_shimizu55","sweetsavage8686", "mhmmad.hazmi", "mr.wilson81", "babmonnier",
 "wildreanna1", "thiagollrocha", "apolobarrel", "wendy.leffler", "a.l.e.7874", "elfonchi", "natuferrari", "patriciobattiato", "oderfla1212", "ozdemirnilduruayca", "isaac_purelife",
 "da.niela7626", "nikola.pan88", "lc_damovich", "rufus_silva", "particlecolada", "tgtaylor8689","adzsomboli", "ali_mohsen_97", "itsjust.justin.x", "mayamohammud", "raqueldegodoy",
 "jansrdjan", "___valoo___", "frommyjourney", "theresalass1244", "cheffantoni.jacaraipe", "muriele.trepak", "jpanter", "andysmith247", "chaves_santt", "rj_carangue", "norlanlucas",
 "gengmp", "casanostre", "fabianormendonca", "thelaughingcrab", "alexvalencia6017", "einfachrauf", "click_waves_2001", "lauro.cunha", "brunotorresgarcia97", "ombaksurftravel", "fincaelachiote",
 "_queen_zolanda_", "viva.ventura", "semaforo.market", "radxhouse_", "_paulbillet_", "natural_soulpg", "jonathanbjj13", "friendsurfhouse", "nomadesviajeros", "cygald", "sajimu_playlists",
 "rasec78", "miss_lucas_lace", "pralon_thiago", "flaubersurf", "wakebrazzers", "myklazer", "matias_ezequiel79", "ptibinaliva", "pervizletfli", "madsenjoel", "tastanovmadiiar",
 "lucasbezerraoficial", "jessonslade", "danieladuim", "railson_oliveirap", "caina_1mano", "laissaldanha_", "guigodr", "marissabruchucontesse", "sleiter_molina", "pablo9761", "catquimr",
 "bloggeurlibre", "aj_gon", "thomas200518", "magomed_salpagarov09", "jose30051986", "ycarlajara", "snakelegs_ocean_apparel", "calibajalife", "juliaguerrac", "sushibarcasadapraia",
 "rafajorgecalifa", "casapraiana_oficial", "chloe52_griezmann_foot_psg", "cengelaylin", "cilene111", "me_kaditya", "galactic_naturalist", "vivaparavion", "amane532", "kleberturismonatal",
 "vilasmohurle", "jeh_24k", "rick_harrison_grimes", "intoxicosvv", "wilian_silveira", "zahara_surf", "anyaevdd", "diotis_surf_school", "rickardogutierrez", "wizard_leather",
 "ameur_bencherif", "matzizcomposer", "surf__010", "ni_putu_michiko", "cristian_fichera_", "wendel949oliveira", "aki.aus", "leahihealth", "richardcbarros.surffotos", "luaninha480",
 "pick.ur.pick", "sylviainacio", "sandrabisi", "toddmarionentertainment", "georgiefaresin", "s.bustamante94", "tripsbygelly", "hemrajbos", "neenapali", "swellness.co", "bastien.ohier",
 "lessurfantsterribles", "tubeyfrank", "vitoyar", "newsp_", "andriiiiiii__", "ashpluggy", "dezquarentagrifesocial", "ook.audiofilm", "yourfuckingrequiem", "tiziana_grdn", "desperatesurferswife",
 "jessebtrevino", "rajdeepsinh._ribda_._", "snowcrunch", "dina.lima17", "conextelecompe", "margarette7777", "joffreyformont", "hugowhereveryougo", "kingcothegreat", "tigre.media",
 "samuraidiogo", "lafrenieremichel", "apollo.natural", "_malusartorio", "tumoanavainui", "kahviana84", "the_tsunamibots", "thegreatdedub", "apryll_jean", "spotify2018", "marcionespule",
 "akgvkite", "rudi_surf", "vianasurf", "massiccio39", "marcelo.l3al", "antoniosu525",  "xavi.nova", "oliverzietz", "thesurfinglifes", "monkeypinkalborada", "ledrocks", "watermarksurf",
 "summeroflove67", "tattoo_one_", "joaozinho__ferdan", "surfinglove.vn", "wellingtonphotographo_alemao", "bomauiman", "carla_rgs", "fotility", "querbiscoitos", "chloe_unicorngirl_123",
 "fabio.fuerte", "brabantvibes", "ninii_nouche", "luizmonteiroflavio", "cleitonfavero", "josealberto0828", "marcusvini_b", "sheilla_bez", "muffischlumpf33", "blake.imperl", "marianahilarino",
 "_justin_nl_", "basofi1888", "kennedy_kxg", "nelsonsr.mike", "marcelobuzi", "rczrnk", "lottiejamesclothing", "kalani_favela", "shamirsilveira", "celine.cheron", "natedizzle13", "mallisurf",
 "tothepowerof.us", "ellemae_23", "nilotycus", "workingclass_second", "sugawara.daichi", "tenuousprotest", "wakedyster", "shizuna.m", "elfrodo_decamoa", "leo_ibanez13", "leilaabdullaeva8368",
 "ritisoul", "jonasfalasco", "tiagojacob81", "best.polarbear.pictures", "soy_mauro_romero", "ezeloure", "isaac.trethewey", "staymalibu1", "ademir_19", "travisg111", "fernandocabecafotos",
 "jacob_strevett", "kalena_sol", "leomotoristaparticular", "sacenach", "yohanborgia", "odontosuldailha", "oshiun", "iv_an5868", "brodie__carroll", "ariewolman", "quebermudaeessa", "radleah",
 "anapguimaro", "lalas.extreme", "duncanrphoto", "luiz_calcadasjr", "baydaw06", "michael_diacomihalis", "marcelocav", "michaelcarbury", "angela_angel_sobral", "sandielove831",
 "citynightphotography", "whiterabbitapparel", "mauzeilmann", "alexezhfilmmaker", "leandro10m24", "davisurf1979", "_surfarariense", "elevenhaircare", "seagypsy001", "mollytrainner1931",
 "langrebeach", "svart_galaxy", "_fabienb10_", "ismwan1382", "hiddenbayresortmentawais", "ethanmonic24", "bobbystorejp", "el_hombreayala", "victorffreire95", "banjobemrose", "alexandreribas67",
 "friedenpete", "xcesarcastroo", "travelplctures", "davedtc", "kennethmf30", "beachcombers", "labengki_nirwana_resort", "ana_rosa_lopes", "carlos.107sul", "tc.livia", "rafaelteixeiraseifert",
 "emilioorlandogomezsanchez2692", "letsgosurfingirls", "george_d.rocha", "craigpbythesea", "apartmentsolarmorocco", "deep2earth", "tonybino29", "mariaceliacallegari", "higor.sc272", "elder_narre",
 "gigglingcactus", "goncalo.firmo", "themindbangerz", "vitorbrigidosurf", "san.tiago5680", "joaorodrigues2121", "sunrisetosunset71", "farms_surf", "smgt1968", "williampro2000", "dallasstanfield",
 "sheilacarvalhosou", "altair.rodriguez05", "laeti_cr", "uniguide1", "leonardolgf83", "abryant17", "travel_brookes", "claudioevangelistaa", "ashhingstonphotography", "joao.m.gomez",
 "name_is_frank_", "carlomercurio", "devid.brandao._001", "africanartdownunder7", "camwalshe", "noffwhite", "helenakoroshetz", "luanabeeh", "giovanoferrari", "we.are.allstars", "tomas_romao",
 "mast_loop_paris", "maxanderson2743", "yboscher", "bungrizki", "cvarner206", "antonio_cervineto", "jupysurfcamp", "andrebeibesauro_surf", "dfabiob", "loud.hound", "gaia_radical", "lsyoann",
 "kobydylan13", "noisreme", "hello_noosaaustralia", "naataan", "mehdi_zouid", "queuetheking", "postoppaddleaustralia", "greenworld_ausserkontrolle", "carlos.tanaonda7724", "baylesstanner",
 "vilaverdeorgan", "sulmarsurfoofc", "vitinhocardoso2004", "serginho.ferraz", "lesgjr", "tanya619suarez", "cloud_shishalounge", "invisiblegoldcoast", "saho5227", "tortoraricardo",
 "shamanized", "calegariorosa", "mafia_deity", "surf_school_ajss_skhirat", "jontempleton", "patosurf_oficial", "shit.h0t", "sosservicosautomotivos", "bodyboarding_taylor", "ilan_salerno2",
 "redwhitle", "rafaell_siillvaa", "trishkearns22", "ihavemates", "seanycarroll", "espacofemininoellas", "destinationfaraway", "notec", "jeffreywerve", "t_roys_adventures", "stylebooy",
 "clar_hayes", "iseeocean", "trackgrowth", "2stepsfromfreedom", "ninomarcucci_stefano", "vaspratasbr", "lexluthergx", "nickricharduk", "bbstoone", "mannello.kirsten", "rafaeldantas_._",
 "taboobeachclub", "ikonoclasta32", "keramas.acessorios.surf", "te.monteiro.f", "uv2505preiss", "lauravvde", "nsbarbosavillar", "blanchbaucells", "xanderocha2015.ar", "sybalita", "swellcolors",
 "leo10tur", "emersonjr1", "lovehodaddy", "jordieto", "samuca_muller", "myjulesriver", "vaniobenetti", "sofiatinocosurf", "leoodonto2007", "wavepalmetto", "movemoretoday", "kurnellgorilla",
 "leo_rodriguesemoraes", "david.n.mitchell", "inter_surf_", "rubsurf32", "troym.johnson", "arci_vale", "surfer_ilan", "leroysoulsurfer", "yarontzoor", "swamissurfer", "wantednoiseca",
 "marco.granisso", "ponokaibeachwear", "charlesbaer21", "momma_blu", "mick_h76", "calebricho_", "jeffurdan", "lukefranco2", "lewdogger", "raonigbarra", "restlessjosie",
 "globalinternetgovernment", "willyjamesson", "rodi013", "lorenewest77", "queen_jovela_siallagan", "zumakooks", "wilsonalaino", "rheegis", "fburini", "santabarbarastoked",
 "alyssa_jutras", "mysurfingsession", "nhecosurf", "thiiinunes", "edvaldo_teteu", "margostosa", "savvanaa.b_13", "tahhinna", "danefadul_", "andre_lucena", "gui_clarindo", "cabedafaria",
 "yanaryr", "belliniguitars", "veronica89biotech", "borrachajuniorm", "charlie.f17", "tomyam63", "empowerment_group", "zgas84", "optcool.water", "makamaeomolokai", "sulawithlove",
 "multientphilly", "arielo.fuentealba", "carbono14oficial", "crislenses", "senhortempobombrinquedos", "flabalbina", "infinitylinhares", "harmonypropertysolutions", "carolripoli",
 "lh.prod", "buyolunsarkisi", "dra.natalliepiana", "venturawave", "t_h_r_o_n_e", "bcdronerealisations", "monsta_surfing", "ivanabolsas", "staubundbeton", "sanamares", "choco.bronze",
 "marviin_santos", "claudiokonrath", "rg.dustin", "boutique_armacao", "emerson_cholby_", "deen.marchese", "allanderinger", "flipzsurfboards", "liquidsouls365", "betosmartins",
 "squimzel", "hqsoundsradio", "purebeachbum", "anfisurfperformance", "renataalvesmakeup1", "manni.skates", "rubaotrofeus", "bymonipeni", "queremosumalinharesmelhor", "personaclinica",
 "simonbbecker", "jujuuca", "junior_onz", "lords.barbeiros", "camilamicroblading", "tiagocoleborne", "elasradicais", "thecoastallife", "dramayracapilaoficial", "ocaraquevoa", "surfsempretrip",
 "virginie_nieto", "riesasakey", "raguiimports", "pranchasfolhadacosta", "lvs_consultoria", "ednaldonene", "svetlana_080880", "honeybeeprojects", "dzengramm", "deniseannebrown",
 "vijendra_lawar", "sel1dkenny", "bloody_1k", "vitoria_pbelo", "puravidafrance", "nomemarcialyahoo.com.br", "ail_2_133", "delcoimbra", "surfsentinel", "railsonparanagua", "aranhavanessa01",
 "rrcircuitofuncional", "alua_handmade_juice",

]

band_or_music = ["kyson_eye", "majesticcasual", "wa_ll_ace", "weareweslee", "bird_gangs", "feinband", "midnightandre", "krownsmusic", "leojamesconroy", "ensisrecords", "colinweeks", "koalamusic_official", "iamdesrocs", "margmusic", "benjaminjamesmusic", "leyyamusic", "soundsofneonoir", "poolsurfers", "elephant_heart", "handsomeassdan", "krisgruen", "starley", "meggiebrownmusic", "revelriesmusic", "carahfaye", "hanna_malon3", "majesticcasual", "florencerosemusic", "eliasabid", "florin.band", "dj_paddle", "vaporizemusic", "supercelofficial", "thedeadrocks", "carolinekole", "brevmusic", "pedsamp", "templetimi", "seatticmusic", "robdrabkin", "timschou", "vive.band", "gkmband", "koralyoung", "galacticwavemusic", "motherwest", "cardsmusic", "teasleymusic", "dancingonpluto", "mattshillmusic", "anthonymanker", "aquiferofficial", "straymonroe", "positionmusic", "aloudonline", "thecrookedkings", "realdjpaige", "thecabportal", "ditchdays", "oiaoiaintermedia", "thetommygunsmusic", "jeffmusic_360", "sureshaker", "ollebirde", "rosiemankato", "brotherolivermusic", "billycadden", "mooritz_s", "d.j.andre", "madhawkes", "mattywavez", "tiinu_music", "mooneye_band", "forenmusic", "gazloganmusic", "giochamba", "permanent_creeps", "ceylonceylonofficial", "matteastonmusic", "badandtheugly", "toledoband", "carissajade.audio", "bambaefx", "flybymidnight", "thezilzies", "fliprushmore", "thedanaleigh", "samshaky", "plastic_messiah", "themoniker", "myfriendtheimmigrant", "adam.g.r.o.s.s", "rexdow", "raftmark_music", "mad.haoles", "ooificial", "rebelkicksmusic", "theaztext", "okanproject", "galapaghostatx", "treadsmusic", "olamusicbranding", "theflavians", "burntband", "hannah_malon3", "cnmaofficial", "officialmcrich", ]
friends = ["pablopansini", "margaretmafra", "henry.k.o", "masterfriends_", "sapucaiaalexandre", "joseluizcremasco", "henriquesapucaia", "juliasapucaia", "beatriz_sapucaia", "marinamosckem", "igor.sapucaia", "joaopaulovbraga","hygorloureiro", "luiz_sapucaia", "ronaldohenriques",  "nathaliabollis", "danielttovar","henriquevsiqueira", "zamazulum", "rebeccacobe", "joanavsiqueira", "fscampini","mayraviegasgomes", "barbarabindeli", "murilosubtilmelo", "lucascandeia", "thigm85", "ericamafra", "brunafpandini", "lucasguerrera10", "rafael_folador", "juliananeis", "anasapucaia", "dallarquitetura", "marcelacurbani", "paola.delleprane", "analuizamafra_",  "biancacalezane", "vsapucaia", "leticiabrainer", "hiroshisk", "bluca8", "gabrielabrettas", "alinecalegario", "sapucaiaelizabeth", "silvinhasapucaia", "cesinhamagno", "danielscampini", ]


shit = ["spotify_promo",]
unkown = ["benjaezequiel1", "detskaya_obuv_odezhda", "iumadi", "nestobangs", "jet._hogenboom", "weare.koala", "jnhndrkv", "matthurray", "climbinglove101", "thetiggyshow", "____anakinskywalker", "ryusuke179", "martinforsell", "farnesioporto", "gfish", "rdfosborne", "xxelvispresleyxx", "dcizco", "delpezzomusic", "malbin34", "moosseoriginal", "xceleurope", "alextravelbucketlist", ]
person_br = [ "danielpcoelho", "pelado__ruiz", "richard_peterson246", "galguedes1", "newton.miranda.5", "robens.pierre.77", "suelencristianedefreitasd", "adriana_navy086", "rodrigobabis", "jaacyoliveira", "beltrao_yuri", "victormferr", "renangobbi19", ]
person_other = ["rene.hernan", "anttunes_marlon", "hiroshiyahagi", "riiozi_", "kaius.skatey", "rabota_sidya__doma_", "leonsaenz46", "olegmikhailov4806", "tonypaul14", "willian_ramon07", "angelorangelcr", "andreamast_09", "romeobhat2", "nathanielhoko","hannah.mary.w", "johnnyhafner", ]
company = ["stoke_surfwear", "paracaidismocordoba", "boulangerpaes", "trintapes", "wanderingwildretreats", "redbubble_haleyd1612", "bonna_delivery", "dpontodebala", "biscoitosdadidi", "ncsurfboards", "ovosrecheadosgp", "casalarvariedades", "openwaters_usa", "picosdesurf", "official.gremmies", "grupo.sensato", "skimvix","ondassurf", "lapsanghouse","surf_of_insta0", "seasonshape", "hankthebusinessman", "rjeffreysurf", ]

